### ISSUE TITLE
mention dependency on nodejs in readme

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/mapzen-docs-generator#101]

**Comment by louh** [comment]
We're actually gonna take out all the npm and node from here

**Comment by louh** [comment]
![hqdefault](https://cloud.githubusercontent.com/assets/2553268/13286079/d802510e-dacc-11e5-9b3d-38b4a3b7c9d1.jpg)

as of https://github.com/mapzen/mapzen-docs-generator/pull/111
