### ISSUE TITLE
Highlight Documentation in page header

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen-docs-generator#120]

**Comment by sleepylemur** [comment]
believe this is a translation of a bug that i saw in precog that turned out to be precog related rather than documentation related, so closing

**Comment by migurski** [comment]
Thanks! How might I fix this in Precog?

**Comment by sleepylemur** [comment]
this script https://github.com/mapzen/styleguide/blob/master/src/scripts/active-nav-link.js is adding the active class to the current page based on regexing the path.
if you want it to work in precog it seems like you have several not great options:
- run a custom version of that script in precog
- change the nav-link script so it supports precog paths as well as mapzen.com paths
- change the header file that's being imported from the styleguide into something that's templated rather then added to the page without modification, which would allow us to hardcode the active path and stop relying on javascript to set it for us, but there are some technical hurdles to overcome before that happens.

**Comment by migurski** [comment]
Ooh, that’s annoying. I feel like this might be better accomplished in some way that’s content rather than path dependent, for example a flag set the front matter.

 :thought_balloon: 
🤔

**Comment by sleepylemur** [comment]
we could make each page responsible for it by inlining a script in the layout that sets the active class... also not really ideal...

**Comment by migurski** [comment]
Yeah.

It’s not hugely important for the time being.
