### ISSUE TITLE
add cloudfront invalidation to deploy

### ISSUE THREAD

**Issue by sleepylemur** [mapzen/mapzen-docs-generator#123]
@migurski what do you want to do here?
the simplest thing to implement is probably something like the deploy/invalidate_cloudfront.sh script in the blog, but just invalidate /documentation/*

i know it's also possible to set "Cache-Control: max-age=" or "Expires" headers in s3, but i'm not sure on the details, and since the bucket is being shared, it'd probably have to be added to all the documentation files on upload.

**Comment by migurski** [comment]
I think each of the static repos that writes to S3 should be doing the same consistent thing, so we don't confuse ourselves with different behaviors. Sounds like you’re on your way to solution in https://github.com/mapzen/blog/pull/859 right?

**Comment by sleepylemur** [comment]
going with 5 minute cache expiration instead of invalidating so closing this.
