### ISSUE TITLE
pagination test preventing apparently-legal nav setup

### ISSUE THREAD

**Issue by meetar** [mapzen/mapzen-docs-generator#138]
I'm trying to change the Tangram docs nav, but the test disabled in https://github.com/mapzen/mapzen-docs-generator/commit/f99c837aec45bc6b97d9c6c860c00535189e2cf1
 is failing, which stops the deployment. With the test off, the build is successful, and the docs look correct:

https://precog.mapzen.com/mapzen/mapzen-docs-generator/2533127/documentation/tangram/

With the test on, it fails here: https://circleci.com/gh/mapzen/mapzen-docs-generator/368

With this error:

    Traceback (most recent call last):
      File "./run-checklist.py", line 127, in test_tangram_index
        self._test_doc_section('/tangram', *self._load_doc_titles('config/tangram.yml'))
      File "./run-checklist.py", line 81, in _test_doc_section
        self.assertIn(next_title, link1.text, 'First pagination link should go to {} from {}'.format(next_title, self.server.url))
    AssertionError: 'Concept Overviews' not found in ' The Scene File  ' : First pagination link should go to Concept Overviews from /tangram/index.html

As far as I can tell from this output, the test expects that on this page:

https://precog.mapzen.com/mapzen/mapzen-docs-generator/2533127/documentation/tangram/Scene-file/

There will be a link to a page called “Concept Overviews”. However that’s a heading under which Scene-file.md is grouped, and not a page. I thought perhaps that meant it expected a heading to have its own page, but mkdocs only allows that if there are no subheadings defined below it in the nav, such as the case of the "JavaScript API” heading: https://precog.mapzen.com/mapzen/mapzen-docs-generator/2533127/documentation/tangram/Javascript-API/

Is this a correct reading, and if so can we change the test? If not, how can I change the code to pass it?

cc @migurski

**Comment by migurski** [comment]
It’s looking at the first item in the configuration file and hoping to find a page with that name, but because there is no .md file for the first item, the test gets confused. I’ll edit the test to better reflect what’s supposed to happen here.

**Comment by meetar** [comment]
👌 👍 ✌️

**Comment by meetar** [comment]
fixed with https://github.com/mapzen/mapzen-docs-generator/commit/f99c837aec45bc6b97d9c6c860c00535189e2cf1
