### ISSUE TITLE
local make fails on mac

### ISSUE THREAD

**Issue by meetar** [mapzen/mapzen-docs-generator#155]
Following the instructions in the README for local bootstrapping (https://github.com/mapzen/mapzen-docs-generator#rapid-bootstrapping), the `make` command fails on a mac at:

`curl -sL https://github.com/mapzen/vector-datasource/archive/v0.10.2.tar.gz | tar -zxv -C src-vector-tiles --strip-components=2 --exclude=README.md --wildcards '*/docs/'`

with the error:

`tar: Option --wildcards is not supported`

**Comment by rmglennon** [comment]
Thanks for testing @meetar, and to @migurski for a fix.
