### ISSUE TITLE
Publish Elevation Tiles docs

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen-docs-generator#186]
https://github.com/tilezen/joerd/pull/88 is the work-in-progress with new Elevation Tiles docs. We already have an Elevation lookup service documented, so getting these into a sensible state may be tricky. We’d like to prevent user confusion while getting these new docs in front of our community.

**Comment by rmglennon** [comment]
The docs are in place, but we need to add it to the documentation homepage when it is officially announced.

**Comment by rmglennon** [comment]
fixed byhttps://github.com/mapzen/mapzen-docs-generator/pull/205
