### ISSUE TITLE
Add libpostal API docs to site

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mapzen-docs-generator#207]
Currently, there is one topic and it lives here: https://github.com/whosonfirst/go-whosonfirst-libpostal/blob/master/docs/index.md

Need to find a home for it. After some discussions, we can put it under Data, similar to Elevation. 

Can update URL in blog when this is done. https://mapzen.com/blog/libpostal/

cc @thisisaaronland

**Comment by thisisaaronland** [comment]
Is there an ETA on this?

**Comment by rmglennon** [comment]
Preview here: https://precog.mapzen.com/mapzen/mapzen-docs-generator/rhonda-add-libpostal/documentation/

cc @kkowalsky

**Comment by thisisaaronland** [comment]
w00t!
