### ISSUE TITLE
can't get anchor tag button to work 

### ISSUE THREAD

**Issue by kkowalsky** [mapzen/mapzen-docs-generator#212]
I couldn't get the copy button for the doc's anchor tags to work on the tangram docs

**Comment by rmglennon** [comment]
Is there a particular page or example where you see this problem, @kkowalsky?

I poked around and clicking the anchor button (hover text of Permanent Link) next to a heading seems to function on Mac/Chrome... It scrolls the page and changes the URL to use a # (https://mapzen.com/documentation/tangram/Javascript-API/#scene). This matches the action when clicking the source in GitHub. Certified works on my machine!

I don't think it has any copy functionality, though. Could you explain what you expect to happen?

**Comment by kkowalsky** [comment]
I guess I thought the anchor tags would also copy the new URL....
