### ISSUE TITLE
Move Search CDN cache description to general Mapzen docs

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen-docs-generator#229]
It's written for [Search now](https://mapzen.com/documentation/search/api-keys-rate-limits/#caching-to-improve-performance) but applies just as much for Vector Tiles.

We should then make reference in the Vector Tiles docs to the new general Mapzen CDN cache description.

**Comment by rmglennon** [comment]
Closing this here, complex issue and will not include it in docs regarding rate limiting.
