### ISSUE TITLE
Docs search preview cuts off words

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mapzen-docs-generator#34]
Looks like it may show just a max number of characters. See if we can control this and be smarter about the text that gets displayed.

![image](https://cloud.githubusercontent.com/assets/4380498/10439339/1b25d4fe-70ee-11e5-8a65-be809a9d7f9f.png)

**Comment by rmglennon** [comment]
@louh - is there a possible fix for this (being as you self-assigned it)? 

Else, I'll close and archive.

**Comment by louh** [comment]
I don't believe this is something we can tackle on our end. It would
involve digging into the guts of MkDocs or seeing if they have fixed /
enabled fixing it in an upgrade. I think we could archive, since this is
likely to return in future work.

**Comment by rmglennon** [comment]
Thanks for the analysis.
