### ISSUE TITLE
Strategy for content in tables (especially for mobile)

### ISSUE THREAD

**Issue by souperneon** [mapzen/mapzen-docs-generator#72]
Figure out some guidelines on creating tables (suggested number of columns and total width) so it is reasonably readable on mobile and doesn't look broken (see below)

![](https://cloud.githubusercontent.com/assets/6125224/10532329/186d0422-738b-11e5-873e-f4783c93c6ed.png)

**Comment by rmglennon** [comment]
Moved to styleguide https://github.com/mapzen/styleguide/issues/215
