### ISSUE TITLE
broken link in elevation.yml

### ISSUE THREAD

**Issue by allisonburtch** [mapzen/mapzen-docs-generator#92]
hey all, I found a 404 on the [elevation](https://mapzen.com/documentation/elevation/) documentation page when you try to click on the "[edit on github](https://github.com/valhalla/valhalla-docs/tree/matrix-help/elevation-service.md)" link.

I believe that a line in [elevation.yml ](https://github.com/mapzen/mapzen-docs-generator/blob/master/config/elevation.yml)needs to be changed from
`docs_base_url:` https://github.com/valhalla/valhalla-docs/tree/matrix-help

to
`docs_base_url:` https://github.com/valhalla/valhalla-docs/blob/master/elevation/

**Comment by rmglennon** [comment]
Thanks!
